steps:
  - command: scripts/docker-cleanup.sh
    label: ":toilet:"

  - command: scripts/build-image.sh
    label: ":hammer: :docker:"
    env:
      BUILDKITE_DOCKER_COMPOSE_CONTAINER: cart-inventory-api

  - wait

  - command: scripts/test-unit.sh
    label: ":eslint: :new_moon_with_face: :partyparrot:"
    env:
      BUILDKITE_DOCKER_COMPOSE_CONTAINER: cart-inventory-api

  - wait

  - command: scripts/test-integration.sh
    label: ":llama:"
    env:
      BUILDKITE_DOCKER_COMPOSE_CONTAINER: cart-inventory-api-test

  - wait

  - command: scripts/check-version.sh
    label: ":point_up:"

  - wait

  - command: scripts/deploy-github.sh
    label: ":rocket: :github:"
    env:
      BUILDKITE_DOCKER_COMPOSE_CONTAINER: cart-inventory-api-test
    branches: master

  - command: scripts/deploy-dockerhub.sh
    label: ":rocket: :docker:"
    branches: master
